package com.example.booktogo.model

data class HotelExplore(
    var addressHotel: String,
    var idHotel : String,
    var levelHotel : String,
    var nameHotel : String,
    var priceRange : String,
    var lat : String,
    var lng : String,
    var details1 : String,
    var details2 : String,
    var details3 : String,
    var details4 : String,
    var details5 : String,
    var details6 : String,
    var details7 : String,
    var details8 : String,
    var details9 : String,
    var nearby1 : String,
    var nearby2 : String,
    var nearby3 : String,
    var nearby4 : String,
    var nearby5 : String,
    var clean_room : String,
    var elevator : String,
    var family : String,
    var free_wifi : String,
    var hot_tub : String,
    var laundry : String,
    var reception : String,
    var security_camera : String,
    var smoke : String
)